module.exports = {
    creep: {
        type: {
            a: [
                {cost:  250, body: [MOVE, MOVE, CARRY, WORK]},
                {cost:  500, body: [MOVE, MOVE, CARRY, WORK, MOVE, MOVE, CARRY, WORK]},
                {cost: 1000, body: [MOVE, MOVE, CARRY, WORK, MOVE, MOVE, CARRY, WORK, MOVE, MOVE, CARRY, WORK, MOVE, MOVE, CARRY, WORK]},
                {cost: 2000, body: [MOVE, MOVE, CARRY, WORK, MOVE, MOVE, CARRY, WORK, MOVE, MOVE, CARRY, WORK, MOVE, MOVE, CARRY, WORK, MOVE, MOVE, CARRY, WORK, MOVE, MOVE, CARRY, WORK, MOVE, MOVE, CARRY, WORK, MOVE, MOVE, CARRY, WORK]},
                {cost: 4000, body: [MOVE, MOVE, CARRY, WORK, MOVE, MOVE, CARRY, WORK, MOVE, MOVE, CARRY, WORK, MOVE, MOVE, CARRY, WORK, MOVE, MOVE, CARRY, WORK, MOVE, MOVE, CARRY, WORK, MOVE, MOVE, CARRY, WORK, MOVE, MOVE, CARRY, WORK, MOVE, MOVE, CARRY, WORK, MOVE, MOVE, CARRY, WORK, MOVE, MOVE, CARRY, WORK, MOVE, MOVE, CARRY, WORK, MOVE, MOVE, CARRY, WORK, MOVE, MOVE, CARRY, WORK, MOVE, MOVE, CARRY, WORK, MOVE, MOVE, CARRY, WORK]},
                {cost: 8000, body: [MOVE, MOVE, CARRY, WORK, MOVE, MOVE, CARRY, WORK, MOVE, MOVE, CARRY, WORK, MOVE, MOVE, CARRY, WORK, MOVE, MOVE, CARRY, WORK, MOVE, MOVE, CARRY, WORK, MOVE, MOVE, CARRY, WORK, MOVE, MOVE, CARRY, WORK, MOVE, MOVE, CARRY, WORK, MOVE, MOVE, CARRY, WORK, MOVE, MOVE, CARRY, WORK, MOVE, MOVE, CARRY, WORK, MOVE, MOVE, CARRY, WORK, MOVE, MOVE, CARRY, WORK, MOVE, MOVE, CARRY, WORK, MOVE, MOVE, CARRY, WORK, MOVE, MOVE, CARRY, WORK, MOVE, MOVE, CARRY, WORK, MOVE, MOVE, CARRY, WORK, MOVE, MOVE, CARRY, WORK, MOVE, MOVE, CARRY, WORK, MOVE, MOVE, CARRY, WORK, MOVE, MOVE, CARRY, WORK, MOVE, MOVE, CARRY, WORK, MOVE, MOVE, CARRY, WORK, MOVE, MOVE, CARRY, WORK, MOVE, MOVE, CARRY, WORK, MOVE, MOVE, CARRY, WORK, MOVE, MOVE, CARRY, WORK, MOVE, MOVE, CARRY, WORK, MOVE, MOVE, CARRY, WORK, MOVE, MOVE, CARRY, WORK]},
            ],
            b: [
                {cost:  200, body: [MOVE, MOVE, CARRY, CARRY]},
                {cost:  400, body: [MOVE, MOVE, CARRY, CARRY, MOVE, MOVE, CARRY, CARRY]},
                {cost:  800, body: [MOVE, MOVE, CARRY, CARRY, MOVE, MOVE, CARRY, CARRY, MOVE, MOVE, CARRY, CARRY, MOVE, MOVE, CARRY, CARRY]},
                {cost: 1600, body: [MOVE, MOVE, CARRY, CARRY, MOVE, MOVE, CARRY, CARRY, MOVE, MOVE, CARRY, CARRY, MOVE, MOVE, CARRY, CARRY, MOVE, MOVE, CARRY, CARRY, MOVE, MOVE, CARRY, CARRY, MOVE, MOVE, CARRY, CARRY, MOVE, MOVE, CARRY, CARRY]},
                {cost: 3200, body: [MOVE, MOVE, CARRY, CARRY, MOVE, MOVE, CARRY, CARRY, MOVE, MOVE, CARRY, CARRY, MOVE, MOVE, CARRY, CARRY, MOVE, MOVE, CARRY, CARRY, MOVE, MOVE, CARRY, CARRY, MOVE, MOVE, CARRY, CARRY, MOVE, MOVE, CARRY, CARRY, MOVE, MOVE, CARRY, CARRY, MOVE, MOVE, CARRY, CARRY, MOVE, MOVE, CARRY, CARRY, MOVE, MOVE, CARRY, CARRY, MOVE, MOVE, CARRY, CARRY, MOVE, MOVE, CARRY, CARRY, MOVE, MOVE, CARRY, CARRY, MOVE, MOVE, CARRY, CARRY]},
                {cost: 6400, body: [MOVE, MOVE, CARRY, CARRY, MOVE, MOVE, CARRY, CARRY, MOVE, MOVE, CARRY, CARRY, MOVE, MOVE, CARRY, CARRY, MOVE, MOVE, CARRY, CARRY, MOVE, MOVE, CARRY, CARRY, MOVE, MOVE, CARRY, CARRY, MOVE, MOVE, CARRY, CARRY, MOVE, MOVE, CARRY, CARRY, MOVE, MOVE, CARRY, CARRY, MOVE, MOVE, CARRY, CARRY, MOVE, MOVE, CARRY, CARRY, MOVE, MOVE, CARRY, CARRY, MOVE, MOVE, CARRY, CARRY, MOVE, MOVE, CARRY, CARRY, MOVE, MOVE, CARRY, CARRY, MOVE, MOVE, CARRY, CARRY, MOVE, MOVE, CARRY, CARRY, MOVE, MOVE, CARRY, CARRY, MOVE, MOVE, CARRY, CARRY, MOVE, MOVE, CARRY, CARRY, MOVE, MOVE, CARRY, CARRY, MOVE, MOVE, CARRY, CARRY, MOVE, MOVE, CARRY, CARRY, MOVE, MOVE, CARRY, CARRY, MOVE, MOVE, CARRY, CARRY, MOVE, MOVE, CARRY, CARRY, MOVE, MOVE, CARRY, CARRY, MOVE, MOVE, CARRY, CARRY, MOVE, MOVE, CARRY, CARRY, MOVE, MOVE, CARRY, CARRY, MOVE, MOVE, CARRY, CARRY]},
            ],
            c: [
                {cost:  900, body: [MOVE, MOVE, MOVE, CARRY, WORK, CLAIM]},
                {cost: 1800, body: [MOVE, MOVE, MOVE, CARRY, WORK, CLAIM, MOVE, MOVE, MOVE, CARRY, WORK, CLAIM]},
                {cost: 3600, body: [MOVE, MOVE, MOVE, CARRY, WORK, CLAIM, MOVE, MOVE, MOVE, CARRY, WORK, CLAIM, MOVE, MOVE, MOVE, CARRY, WORK, CLAIM, MOVE, MOVE, MOVE, CARRY, WORK, CLAIM]},
                {cost: 7200, body: [MOVE, MOVE, MOVE, CARRY, WORK, CLAIM, MOVE, MOVE, MOVE, CARRY, WORK, CLAIM, MOVE, MOVE, MOVE, CARRY, WORK, CLAIM, MOVE, MOVE, MOVE, CARRY, WORK, CLAIM, MOVE, MOVE, MOVE, CARRY, WORK, CLAIM, MOVE, MOVE, MOVE, CARRY, WORK, CLAIM, MOVE, MOVE, MOVE, CARRY, WORK, CLAIM, MOVE, MOVE, MOVE, CARRY, WORK, CLAIM]},
            ],
        },
        role: {
            harvester: {
                defaultAmount: 2,
                creepType: 'a',
            },
            builder: {
                defaultAmount: 2,
                creepType: 'a',
            },
            upgrader: {
                defaultAmount: 1,
                creepType: 'a',
            },
            transporter: {
                defaultAmount: 2,
                creepType: 'b',
            },
            roomClaimer: {
                defaultAmount: 5,
                creepType: 'c',
            },
        },
    },
};
