module.exports = {
	debug: true,
	cpu: false,
	maxConstructionSites: 2,
	pathUseMinimumTimesUsed: 10,
	pathUseRemoveAge: 100,
	renewTimes: 3,
	renewFrom: 50,
	renewTo: 1000,
	claimRoomController: '55c34a6b5be41a0a6e80c70f',
	creepTypeCount: {
		A: 8,
		B: 0,
		C: 0,
	},
	job: {
		spawnSupply:		{ count: 1, priority: 1},
		containerHarvest:	{ count: 1, priority: 2},
		towerSupply:		{ count: 1, priority: 2},
		linkSupply:			{ count: 1, priority: 3},
		repair:				{ count: 1, priority: 3},
		build:				{ count: 2, priority: 4},
		storageHarvest:		{ count: 1, priority: 5},
		mineralHarvest:		{ count: 1, priority: 5, unassignOnReload: true},
		upgrade:			{ count: 3, priority: 5},
		claim:				{ count: 1, priority: 5},
	},
};
